import { EmptyState } from '@/components/ui'

export function WorkspacePlaceholderPanel({ title }: { title: string }) {
  return (
    <EmptyState
      title={`No ${title.toLowerCase()} available yet`}
      description="Records for this workspace tab will appear here when they are created, linked, or generated by governed activity."
      density="compact"
    />
  )
}
